#
# Copyright (C) 2016 Redhat
#
# Author: Erwan Velu <erwan@redhat.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

import os
import pprint
import unittest
from git_stats import stats


class TestStats(unittest.TestCase):
    
    def test_get_json(self):
        json_struct = [{u'author': {u'avatar_url': u'https://avatars.githubusercontent.com/u/59071?v=3',
              u'events_url': u'https://api.github.com/users/tchaikov/events{/privacy}',
              u'followers_url': u'https://api.github.com/users/tchaikov/followers',
              u'following_url': u'https://api.github.com/users/tchaikov/following{/other_user}',
              u'gists_url': u'https://api.github.com/users/tchaikov/gists{/gist_id}',
              u'gravatar_id': u'',
              u'html_url': u'https://github.com/tchaikov',
              u'id': 59071,
              u'login': u'tchaikov',
              u'organizations_url': u'https://api.github.com/users/tchaikov/orgs',
              u'received_events_url': u'https://api.github.com/users/tchaikov/received_events',
              u'repos_url': u'https://api.github.com/users/tchaikov/repos',
              u'site_admin': False,
              u'starred_url': u'https://api.github.com/users/tchaikov/starred{/owner}{/repo}',
              u'subscriptions_url': u'https://api.github.com/users/tchaikov/subscriptions',
              u'type': u'User',
              u'url': u'https://api.github.com/users/tchaikov'},
  u'comments_url': u'https://api.github.com/repos/ceph/ceph/commits/64c1d54354a09a8485193dce9d5da1c526d1aadd/comments',
  u'commit': {u'author': {u'date': u'2016-02-16T14:04:24Z',
                          u'email': u'tchaikov@gmail.com',
                          u'name': u'Kefu Chai'},
              u'comment_count': 0,
              u'committer': {u'date': u'2016-02-16T14:04:24Z',
                             u'email': u'tchaikov@gmail.com',
                             u'name': u'Kefu Chai'},
              u'message': u'Merge pull request #7520 from renhwsky/renhw-wip-mon-monitor\n\nmon/monitor: some clean up\r\n\r\nReviewed-by: Joao Eduardo Luis <joao@suse.de>\r\nReviewed-by: Kefu Chai <kchai@redhat.com>',
              u'tree': {u'sha': u'900fe1a330d897b421fcf743f28315aa7c33088c',
                        u'url': u'https://api.github.com/repos/ceph/ceph/git/trees/900fe1a330d897b421fcf743f28315aa7c33088c'},
              u'url': u'https://api.github.com/repos/ceph/ceph/git/commits/64c1d54354a09a8485193dce9d5da1c526d1aadd'},
  u'committer': {u'avatar_url': u'https://avatars.githubusercontent.com/u/59071?v=3',
                 u'events_url': u'https://api.github.com/users/tchaikov/events{/privacy}',
                 u'followers_url': u'https://api.github.com/users/tchaikov/followers',
                 u'following_url': u'https://api.github.com/users/tchaikov/following{/other_user}',
                 u'gists_url': u'https://api.github.com/users/tchaikov/gists{/gist_id}',
                 u'gravatar_id': u'',
                 u'html_url': u'https://github.com/tchaikov',
                 u'id': 59071,
                 u'login': u'tchaikov',
                 u'organizations_url': u'https://api.github.com/users/tchaikov/orgs',
                 u'received_events_url': u'https://api.github.com/users/tchaikov/received_events',
                 u'repos_url': u'https://api.github.com/users/tchaikov/repos',
                 u'site_admin': False,
                 u'starred_url': u'https://api.github.com/users/tchaikov/starred{/owner}{/repo}',
                 u'subscriptions_url': u'https://api.github.com/users/tchaikov/subscriptions',
                 u'type': u'User',
                 u'url': u'https://api.github.com/users/tchaikov'},
  u'html_url': u'https://github.com/ceph/ceph/commit/64c1d54354a09a8485193dce9d5da1c526d1aadd',
  u'parents': [{u'html_url': u'https://github.com/ceph/ceph/commit/fd4d97c027c7019bae5a5e72715ad10cd7edbcfa',
                u'sha': u'fd4d97c027c7019bae5a5e72715ad10cd7edbcfa',
                u'url': u'https://api.github.com/repos/ceph/ceph/commits/fd4d97c027c7019bae5a5e72715ad10cd7edbcfa'},
               {u'html_url': u'https://github.com/ceph/ceph/commit/0cef323931816f0699e228be456dbfaa2bb43188',
                u'sha': u'0cef323931816f0699e228be456dbfaa2bb43188',
                u'url': u'https://api.github.com/repos/ceph/ceph/commits/0cef323931816f0699e228be456dbfaa2bb43188'}],
  u'sha': u'64c1d54354a09a8485193dce9d5da1c526d1aadd',
  u'url': u'https://api.github.com/repos/ceph/ceph/commits/64c1d54354a09a8485193dce9d5da1c526d1aadd'},
 {u'author': {u'avatar_url': u'https://avatars.githubusercontent.com/u/908479?v=3',
              u'events_url': u'https://api.github.com/users/gregsfortytwo/events{/privacy}',
              u'followers_url': u'https://api.github.com/users/gregsfortytwo/followers',
              u'following_url': u'https://api.github.com/users/gregsfortytwo/following{/other_user}',
              u'gists_url': u'https://api.github.com/users/gregsfortytwo/gists{/gist_id}',
              u'gravatar_id': u'',
              u'html_url': u'https://github.com/gregsfortytwo',
              u'id': 908479,
              u'login': u'gregsfortytwo',
              u'organizations_url': u'https://api.github.com/users/gregsfortytwo/orgs',
              u'received_events_url': u'https://api.github.com/users/gregsfortytwo/received_events',
              u'repos_url': u'https://api.github.com/users/gregsfortytwo/repos',
              u'site_admin': False,
              u'starred_url': u'https://api.github.com/users/gregsfortytwo/starred{/owner}{/repo}',
              u'subscriptions_url': u'https://api.github.com/users/gregsfortytwo/subscriptions',
              u'type': u'User',
              u'url': u'https://api.github.com/users/gregsfortytwo'},
  u'comments_url': u'https://api.github.com/repos/ceph/ceph/commits/fd4d97c027c7019bae5a5e72715ad10cd7edbcfa/comments',
  u'commit': {u'author': {u'date': u'2016-02-16T04:39:55Z',
                          u'email': u'greg@gregs42.com',
                          u'name': u'Gregory Farnum'},
              u'comment_count': 0,
              u'committer': {u'date': u'2016-02-16T04:39:55Z',
                             u'email': u'greg@gregs42.com',
                             u'name': u'Gregory Farnum'},
              u'message': u'Merge pull request #7629 from ceph/wip-14750-op-timeouts\n\nObjecter: detect laggy ops with objecter_timeout, not osd_timeout\r\n\r\nReviewed-by: Adam C. Emerson <aemerson@redhat.com>',
              u'tree': {u'sha': u'7bb0f70426638fe53271eb682ba353e9362c478a',
                        u'url': u'https://api.github.com/repos/ceph/ceph/git/trees/7bb0f70426638fe53271eb682ba353e9362c478a'},
              u'url': u'https://api.github.com/repos/ceph/ceph/git/commits/fd4d97c027c7019bae5a5e72715ad10cd7edbcfa'},
  u'committer': {u'avatar_url': u'https://avatars.githubusercontent.com/u/908479?v=3',
                 u'events_url': u'https://api.github.com/users/gregsfortytwo/events{/privacy}',
                 u'followers_url': u'https://api.github.com/users/gregsfortytwo/followers',
                 u'following_url': u'https://api.github.com/users/gregsfortytwo/following{/other_user}',
                 u'gists_url': u'https://api.github.com/users/gregsfortytwo/gists{/gist_id}',
                 u'gravatar_id': u'',
                 u'html_url': u'https://github.com/gregsfortytwo',
                 u'id': 908479,
                 u'login': u'gregsfortytwo',
                 u'organizations_url': u'https://api.github.com/users/gregsfortytwo/orgs',
                 u'received_events_url': u'https://api.github.com/users/gregsfortytwo/received_events',
                 u'repos_url': u'https://api.github.com/users/gregsfortytwo/repos',
                 u'site_admin': False,
                 u'starred_url': u'https://api.github.com/users/gregsfortytwo/starred{/owner}{/repo}',
                 u'subscriptions_url': u'https://api.github.com/users/gregsfortytwo/subscriptions',
                 u'type': u'User',
                 u'url': u'https://api.github.com/users/gregsfortytwo'},
  u'html_url': u'https://github.com/ceph/ceph/commit/fd4d97c027c7019bae5a5e72715ad10cd7edbcfa',
  u'parents': [{u'html_url': u'https://github.com/ceph/ceph/commit/0284090464a144ee9cdbe74733b5579a5402fa05',
                u'sha': u'0284090464a144ee9cdbe74733b5579a5402fa05',
                u'url': u'https://api.github.com/repos/ceph/ceph/commits/0284090464a144ee9cdbe74733b5579a5402fa05'},
               {u'html_url': u'https://github.com/ceph/ceph/commit/892c1448c2afbca05dd7f3899afd2c3187e536b9',
                u'sha': u'892c1448c2afbca05dd7f3899afd2c3187e536b9',
                u'url': u'https://api.github.com/repos/ceph/ceph/commits/892c1448c2afbca05dd7f3899afd2c3187e536b9'}],
  u'sha': u'fd4d97c027c7019bae5a5e72715ad10cd7edbcfa',
  u'url': u'https://api.github.com/repos/ceph/ceph/commits/fd4d97c027c7019bae5a5e72715ad10cd7edbcfa'},
 {u'author': {u'avatar_url': u'https://avatars.githubusercontent.com/u/908479?v=3',
              u'events_url': u'https://api.github.com/users/gregsfortytwo/events{/privacy}',
              u'followers_url': u'https://api.github.com/users/gregsfortytwo/followers',
              u'following_url': u'https://api.github.com/users/gregsfortytwo/following{/other_user}',
              u'gists_url': u'https://api.github.com/users/gregsfortytwo/gists{/gist_id}',
              u'gravatar_id': u'',
              u'html_url': u'https://github.com/gregsfortytwo',
              u'id': 908479,
              u'login': u'gregsfortytwo',
              u'organizations_url': u'https://api.github.com/users/gregsfortytwo/orgs',
              u'received_events_url': u'https://api.github.com/users/gregsfortytwo/received_events',
              u'repos_url': u'https://api.github.com/users/gregsfortytwo/repos',
              u'site_admin': False,
              u'starred_url': u'https://api.github.com/users/gregsfortytwo/starred{/owner}{/repo}',
              u'subscriptions_url': u'https://api.github.com/users/gregsfortytwo/subscriptions',
              u'type': u'User',
              u'url': u'https://api.github.com/users/gregsfortytwo'},
  u'comments_url': u'https://api.github.com/repos/ceph/ceph/commits/0284090464a144ee9cdbe74733b5579a5402fa05/comments',
  u'commit': {u'author': {u'date': u'2016-02-16T04:36:47Z',
                          u'email': u'greg@gregs42.com',
                          u'name': u'Gregory Farnum'},
              u'comment_count': 0,
              u'committer': {u'date': u'2016-02-16T04:36:47Z',
                             u'email': u'greg@gregs42.com',
                             u'name': u'Gregory Farnum'},
              u'message': u'Merge pull request #7655 from gregsfortytwo/wip-metarequest-lock\n\nclient: removed unused Mutex from MetaRequest\r\n\r\nReviewed-by: Yan, Zheng <zyan@redhat.com>',
              u'tree': {u'sha': u'91a105cc3e8e190b026de69ef2482df035ce34a3',
                        u'url': u'https://api.github.com/repos/ceph/ceph/git/trees/91a105cc3e8e190b026de69ef2482df035ce34a3'},
              u'url': u'https://api.github.com/repos/ceph/ceph/git/commits/0284090464a144ee9cdbe74733b5579a5402fa05'},
  u'committer': {u'avatar_url': u'https://avatars.githubusercontent.com/u/908479?v=3',
                 u'events_url': u'https://api.github.com/users/gregsfortytwo/events{/privacy}',
                 u'followers_url': u'https://api.github.com/users/gregsfortytwo/followers',
                 u'following_url': u'https://api.github.com/users/gregsfortytwo/following{/other_user}',
                 u'gists_url': u'https://api.github.com/users/gregsfortytwo/gists{/gist_id}',
                 u'gravatar_id': u'',
                 u'html_url': u'https://github.com/gregsfortytwo',
                 u'id': 908479,
                 u'login': u'gregsfortytwo',
                 u'organizations_url': u'https://api.github.com/users/gregsfortytwo/orgs',
                 u'received_events_url': u'https://api.github.com/users/gregsfortytwo/received_events',
                 u'repos_url': u'https://api.github.com/users/gregsfortytwo/repos',
                 u'site_admin': False,
                 u'starred_url': u'https://api.github.com/users/gregsfortytwo/starred{/owner}{/repo}',
                 u'subscriptions_url': u'https://api.github.com/users/gregsfortytwo/subscriptions',
                 u'type': u'User',
                 u'url': u'https://api.github.com/users/gregsfortytwo'},
  u'html_url': u'https://github.com/ceph/ceph/commit/0284090464a144ee9cdbe74733b5579a5402fa05',
  u'parents': [{u'html_url': u'https://github.com/ceph/ceph/commit/42afb5b523e3253d0d2fb94252af9df45c964377',
                u'sha': u'42afb5b523e3253d0d2fb94252af9df45c964377',
                u'url': u'https://api.github.com/repos/ceph/ceph/commits/42afb5b523e3253d0d2fb94252af9df45c964377'},
               {u'html_url': u'https://github.com/ceph/ceph/commit/1ce0c7719ee70e98abc5e2a6124aee430876cf53',
                u'sha': u'1ce0c7719ee70e98abc5e2a6124aee430876cf53',
                u'url': u'https://api.github.com/repos/ceph/ceph/commits/1ce0c7719ee70e98abc5e2a6124aee430876cf53'}],
  u'sha': u'0284090464a144ee9cdbe74733b5579a5402fa05',
  u'url': u'https://api.github.com/repos/ceph/ceph/commits/0284090464a144ee9cdbe74733b5579a5402fa05'},
 {u'author': {u'avatar_url': u'https://avatars.githubusercontent.com/u/908479?v=3',
              u'events_url': u'https://api.github.com/users/gregsfortytwo/events{/privacy}',
              u'followers_url': u'https://api.github.com/users/gregsfortytwo/followers',
              u'following_url': u'https://api.github.com/users/gregsfortytwo/following{/other_user}',
              u'gists_url': u'https://api.github.com/users/gregsfortytwo/gists{/gist_id}',
              u'gravatar_id': u'',
              u'html_url': u'https://github.com/gregsfortytwo',
              u'id': 908479,
              u'login': u'gregsfortytwo',
              u'organizations_url': u'https://api.github.com/users/gregsfortytwo/orgs',
              u'received_events_url': u'https://api.github.com/users/gregsfortytwo/received_events',
              u'repos_url': u'https://api.github.com/users/gregsfortytwo/repos',
              u'site_admin': False,
              u'starred_url': u'https://api.github.com/users/gregsfortytwo/starred{/owner}{/repo}',
              u'subscriptions_url': u'https://api.github.com/users/gregsfortytwo/subscriptions',
              u'type': u'User',
              u'url': u'https://api.github.com/users/gregsfortytwo'},
  u'comments_url': u'https://api.github.com/repos/ceph/ceph/commits/42afb5b523e3253d0d2fb94252af9df45c964377/comments',
  u'commit': {u'author': {u'date': u'2016-02-16T04:35:32Z',
                          u'email': u'greg@gregs42.com',
                          u'name': u'Gregory Farnum'},
              u'comment_count': 0,
              u'committer': {u'date': u'2016-02-16T04:35:32Z',
                             u'email': u'greg@gregs42.com',
                             u'name': u'Gregory Farnum'},
              u'message': u"Merge pull request #7616 from gregsfortytwo/wip-timer-14697\n\nmds: don't double-shutdown the timer when suiciding\r\n\r\nReviewed-by: John Spray <john.spray@redhat.com>",
              u'tree': {u'sha': u'596f48fc562f62206182d49d34944520815a2850',
                        u'url': u'https://api.github.com/repos/ceph/ceph/git/trees/596f48fc562f62206182d49d34944520815a2850'},
              u'url': u'https://api.github.com/repos/ceph/ceph/git/commits/42afb5b523e3253d0d2fb94252af9df45c964377'},
  u'committer': {u'avatar_url': u'https://avatars.githubusercontent.com/u/908479?v=3',
                 u'events_url': u'https://api.github.com/users/gregsfortytwo/events{/privacy}',
                 u'followers_url': u'https://api.github.com/users/gregsfortytwo/followers',
                 u'following_url': u'https://api.github.com/users/gregsfortytwo/following{/other_user}',
                 u'gists_url': u'https://api.github.com/users/gregsfortytwo/gists{/gist_id}',
                 u'gravatar_id': u'',
                 u'html_url': u'https://github.com/gregsfortytwo',
                 u'id': 908479,
                 u'login': u'gregsfortytwo',
                 u'organizations_url': u'https://api.github.com/users/gregsfortytwo/orgs',
                 u'received_events_url': u'https://api.github.com/users/gregsfortytwo/received_events',
                 u'repos_url': u'https://api.github.com/users/gregsfortytwo/repos',
                 u'site_admin': False,
                 u'starred_url': u'https://api.github.com/users/gregsfortytwo/starred{/owner}{/repo}',
                 u'subscriptions_url': u'https://api.github.com/users/gregsfortytwo/subscriptions',
                 u'type': u'User',
                 u'url': u'https://api.github.com/users/gregsfortytwo'},
  u'html_url': u'https://github.com/ceph/ceph/commit/42afb5b523e3253d0d2fb94252af9df45c964377',
  u'parents': [{u'html_url': u'https://github.com/ceph/ceph/commit/da834412012359fe1fa3ba706638a157584d6fba',
                u'sha': u'da834412012359fe1fa3ba706638a157584d6fba',
                u'url': u'https://api.github.com/repos/ceph/ceph/commits/da834412012359fe1fa3ba706638a157584d6fba'},
               {u'html_url': u'https://github.com/ceph/ceph/commit/038005464525607ceab14b55ee7229b522053f8f',
                u'sha': u'038005464525607ceab14b55ee7229b522053f8f',
                u'url': u'https://api.github.com/repos/ceph/ceph/commits/038005464525607ceab14b55ee7229b522053f8f'}],
  u'sha': u'42afb5b523e3253d0d2fb94252af9df45c964377',
  u'url': u'https://api.github.com/repos/ceph/ceph/commits/42afb5b523e3253d0d2fb94252af9df45c964377'},
 {u'author': {u'avatar_url': u'https://avatars.githubusercontent.com/u/908479?v=3',
              u'events_url': u'https://api.github.com/users/gregsfortytwo/events{/privacy}',
              u'followers_url': u'https://api.github.com/users/gregsfortytwo/followers',
              u'following_url': u'https://api.github.com/users/gregsfortytwo/following{/other_user}',
              u'gists_url': u'https://api.github.com/users/gregsfortytwo/gists{/gist_id}',
              u'gravatar_id': u'',
              u'html_url': u'https://github.com/gregsfortytwo',
              u'id': 908479,
              u'login': u'gregsfortytwo',
              u'organizations_url': u'https://api.github.com/users/gregsfortytwo/orgs',
              u'received_events_url': u'https://api.github.com/users/gregsfortytwo/received_events',
              u'repos_url': u'https://api.github.com/users/gregsfortytwo/repos',
              u'site_admin': False,
              u'starred_url': u'https://api.github.com/users/gregsfortytwo/starred{/owner}{/repo}',
              u'subscriptions_url': u'https://api.github.com/users/gregsfortytwo/subscriptions',
              u'type': u'User',
              u'url': u'https://api.github.com/users/gregsfortytwo'},
  u'comments_url': u'https://api.github.com/repos/ceph/ceph/commits/da834412012359fe1fa3ba706638a157584d6fba/comments',
  u'commit': {u'author': {u'date': u'2016-02-16T04:34:43Z',
                          u'email': u'greg@gregs42.com',
                          u'name': u'Gregory Farnum'},
              u'comment_count': 0,
              u'committer': {u'date': u'2016-02-16T04:34:43Z',
                             u'email': u'greg@gregs42.com',
                             u'name': u'Gregory Farnum'},
              u'message': u"Merge pull request #7490 from x11562/mds_mdstype_ref\n\nmds: function parameter 'df' should be passed by reference\r\n\r\nReviewed-by: Greg Farnum <gfarnum@redhat.com>",
              u'tree': {u'sha': u'bd2bc55032fdcf78cee9922c8cf5fc9b6f8109b0',
                        u'url': u'https://api.github.com/repos/ceph/ceph/git/trees/bd2bc55032fdcf78cee9922c8cf5fc9b6f8109b0'},
              u'url': u'https://api.github.com/repos/ceph/ceph/git/commits/da834412012359fe1fa3ba706638a157584d6fba'},
  u'committer': {u'avatar_url': u'https://avatars.githubusercontent.com/u/908479?v=3',
                 u'events_url': u'https://api.github.com/users/gregsfortytwo/events{/privacy}',
                 u'followers_url': u'https://api.github.com/users/gregsfortytwo/followers',
                 u'following_url': u'https://api.github.com/users/gregsfortytwo/following{/other_user}',
                 u'gists_url': u'https://api.github.com/users/gregsfortytwo/gists{/gist_id}',
                 u'gravatar_id': u'',
                 u'html_url': u'https://github.com/gregsfortytwo',
                 u'id': 908479,
                 u'login': u'gregsfortytwo',
                 u'organizations_url': u'https://api.github.com/users/gregsfortytwo/orgs',
                 u'received_events_url': u'https://api.github.com/users/gregsfortytwo/received_events',
                 u'repos_url': u'https://api.github.com/users/gregsfortytwo/repos',
                 u'site_admin': False,
                 u'starred_url': u'https://api.github.com/users/gregsfortytwo/starred{/owner}{/repo}',
                 u'subscriptions_url': u'https://api.github.com/users/gregsfortytwo/subscriptions',
                 u'type': u'User',
                 u'url': u'https://api.github.com/users/gregsfortytwo'},
  u'html_url': u'https://github.com/ceph/ceph/commit/da834412012359fe1fa3ba706638a157584d6fba',
  u'parents': [{u'html_url': u'https://github.com/ceph/ceph/commit/9d2c7869669d6edbf17dc31fd5fb1a0b962f360c',
                u'sha': u'9d2c7869669d6edbf17dc31fd5fb1a0b962f360c',
                u'url': u'https://api.github.com/repos/ceph/ceph/commits/9d2c7869669d6edbf17dc31fd5fb1a0b962f360c'},
               {u'html_url': u'https://github.com/ceph/ceph/commit/8167a22f3d28c2a31a7187cd726f5a450effa012',
                u'sha': u'8167a22f3d28c2a31a7187cd726f5a450effa012',
                u'url': u'https://api.github.com/repos/ceph/ceph/commits/8167a22f3d28c2a31a7187cd726f5a450effa012'}],
  u'sha': u'da834412012359fe1fa3ba706638a157584d6fba',
  u'url': u'https://api.github.com/repos/ceph/ceph/commits/da834412012359fe1fa3ba706638a157584d6fba'}]
 
        data = stats.to_json(stats.get_raw_file("file://%s/git_stats/tests/sample_commits" %
            os.getcwd()))
        self.assertEqual(data, json_struct)

if __name__ == "__main__":
    unittest.main()
